// Import type definitions for Next.js metadata
import type { Metadata } from "next";

// Import custom Google fonts using Next.js font optimization
import { Geist, Geist_Mono } from "next/font/google";

// Import global CSS styles
import "./globals.css";

// Initialize the Geist Sans font and map it to a CSS variable
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Initialize the Geist Mono font and map it to a CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the entire application
export const metadata: Metadata = {
  title: "OrderBook-Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
